<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MedicinesSeeder extends Seeder
{
    public function run()
    {
        DB::table('medicines')->insert([
            [
                'en_name' => 'acetylcistein 200 mg 10 sachet',
                'ar_name' => 'استيل سيستايين فوار 200مجم 10 اكياس',
                'price' => 30,
                'scientific_name' => 'acetylcysteine',
                'medicine_company_id' => 50,
                'usage' => 'mucolytic',
                'units_number' => 10,
                'medicine_unit_id' => 9,
                'barcode' => '6221042202014',
            ],
            [
                'en_name' => 'acetylcistein 600mg 10 eff. instant gran. sachets',
                'ar_name' => 'استيل سيستايين 600مجم فوار 10 اكياس',
                'price' => 45,
                'scientific_name' => 'acetylcysteine',
                'medicine_company_id' => 50,
                'usage' => 'mucolytic',
                'units_number' => 10,
                'medicine_unit_id' => 9,
                'barcode' => '6221042216011',
            ],
            [
                'en_name' => 'abimol 500 mg 20 tab.',
                'ar_name' => 'ابيمول 500مجم 20 قرص',
                'price' => 13,
                'scientific_name' => 'paracetamol(acetaminophen)',
                'medicine_company_id' => 26,
                'usage' => 'antipyretic.analgesic',
                'units_number' => 2,
                'medicine_unit_id' => 15,
                'barcode' => '6221045000341',
            ],
            [
                'en_name' => 'abimol 150mg/5ml syrup 125ml',
                'ar_name' => 'ابيمول 150مجم/5مل 125 مل شراب',
                'price' => 5,
                'scientific_name' => 'paracetamol(acetaminophen)',
                'medicine_company_id' => 26,
                'usage' => 'antipyretic.analgesic',
                'units_number' => 1,
                'medicine_unit_id' => 14,
                'barcode' => '6221045000600',
            ],
            [
                'en_name' => 'abimol 300mg 5 rectal supp.',
                'ar_name' => 'ابيمول 300مجم لبوس 5 اقماع شرجية',
                'price' => 15,
                'scientific_name' => 'paracetamol(acetaminophen)',
                'medicine_company_id' => 26,
                'usage' => 'antipyretic.analgesic',
                'units_number' => 1,
                'medicine_unit_id' => 12,
                'barcode' => '6221045000808',
            ],
            [
                'en_name' => 'abilaxine 5 mg 20 coated tab.',
                'ar_name' => 'ابيلاكسين 5مجم 20 قرص',
                'price' => 4.5,
                'scientific_name' => 'bisacodyl',
                'medicine_company_id' => 26,
                'usage' => 'laxative',
                'units_number' => 2,
                'medicine_unit_id' => 15,
                'barcode' => '6221045000839',
            ],
            [
                'en_name' => 'abimol extra 20 tab.',
                'ar_name' => 'ابيمول اكسترا 500مجم 20 قرص',
                'price' => 16,
                'scientific_name' => 'caffeine+paracetamol',
                'medicine_company_id' => 26,
                'usage' => 'analgesic.antipyretic.headache',
                'units_number' => 2,
                'medicine_unit_id' => 15,
                'barcode' => '6221045011101',
            ],
            [
                'en_name' => 'achtenon 2 mg 30 tabs.',
                'ar_name' => 'اكتينون 2مجم 30 قرص',
                'price' => 34.5,
                'scientific_name' => 'biperidene',
                'medicine_company_id' => 8,
                'usage' => 'antiparkinson agents. muscarinic antagonist.neuro',
                'units_number' => 3,
                'medicine_unit_id' => 15,
                'barcode' => '6221060005239',
            ],
            [
                'en_name' => 'a-viton 50.000 i.u. 20 caps.',
                'ar_name' => 'ا-فيتون 50000 وحدة دولية 20 كبسولة',
                'price' => 19,
                'scientific_name' => 'vitamin a',
                'medicine_company_id' => 32,
                'usage' => 'vitamin a',
                'units_number' => 1,
                'medicine_unit_id' => 2,
                'barcode' => '6221068101001',
            ],
            [
                'en_name' => 'acetaprofen 100ml susp.',
                'ar_name' => 'اسيتابروفين 100 مل معلق',
                'price' => 5,
                'scientific_name' => 'ibuprofen+paracetamol',
                'medicine_company_id' => 32,
                'usage' => 'analgesic.antipyretic',
                'units_number' => 1,
                'medicine_unit_id' => 12,
                'barcode' => '6221068402993',
            ],
            [
                'en_name' => 'acicone 720 mg 20 chew. tab.',
                'ar_name' => 'اسيكون 720مجم 24 قرص للمضغ',
                'price' => 28.5,
                'scientific_name' => 'magaldrate',
                'medicine_company_id' => 39,
                'usage' => 'antacid',
                'units_number' => 2,
                'medicine_unit_id' => 15,
                'barcode' => '6221508014014',
            ],
            [
                'en_name' => 'acicone-s 720/25mg 20 chew. tab',
                'ar_name' => 'اسيكون-اس 720/25مجم 20 قرص مضغ',
                'price' => 6.5,
                'scientific_name' => 'magaldrate+simethicone',
                'medicine_company_id' => 39,
                'usage' => 'antacid',
                'units_number' => 2,
                'medicine_unit_id' => 15,
                'barcode' => '6221508014519',
            ],
            [
                'en_name' => 'acicone susp. 200 ml',
                'ar_name' => 'اسيكون 200 مل معلق',
                'price' => 7.5,
                'scientific_name' => 'magaldrate',
                'medicine_company_id' => 39,
                'usage' => 'antacid',
                'units_number' => 1,
                'medicine_unit_id' => 12,
                'barcode' => '6221508060912',
            ],
            [
                'en_name' => 'acicone-s oral susp. 200ml',
                'ar_name' => 'اسيكون-اس 200 مل معلق',
                'price' => 8,
                'scientific_name' => 'magaldrate+simethicone',
                'medicine_company_id' => 39,
                'usage' => 'antacid',
                'units_number' => 1,
                'medicine_unit_id' => 12,
                'barcode' => '6221508061018',
            ],
            [
                'en_name' => 'acivirax 800mg 20 tabs.',
                'ar_name' => 'اسيفيراكس 800مجم 20 قرص',
                'price' => 107,
                'scientific_name' => 'acyclovir',
                'medicine_company_id' => 37,
                'usage' => 'anti-viral.nucleoside',
                'units_number' => 2,
                'medicine_unit_id' => 15,
                'barcode' => '6222001407808',
            ],
            [
                'en_name' => 'acc long 600mg 5 effervescent tab.',
                'ar_name' => 'ايه سي سي لونج 600مجم 5 اقراص فوارة',
                'price' => 30,
                'scientific_name' => 'acetylcysteine',
                'medicine_company_id' => 38,
                'usage' => 'mucolytic',
                'units_number' => 1,
                'medicine_unit_id' => 4,
                'barcode' => '6222003701553',
            ],
            [
                'en_name' => 'acc 200mg 20 sachets',
                'ar_name' => 'ايه سي سي 200مجم 20 كيس',
                'price' => 28,
                'scientific_name' => 'acetylcysteine',
                'medicine_company_id' => 38,
                'usage' => 'mucolytic',
                'units_number' => 20,
                'medicine_unit_id' => 9,
                'barcode' => '6222003701560',
            ],
            [
                'en_name' => 'abilify 15 mg 10 tabs.',
                'ar_name' => 'ابيليفاي 15مجم 10 اقراص',
                'price' => 330.5,
                'scientific_name' => 'aripiprazole',
                'medicine_company_id' => 42,
                'usage' => 'psychiatric.antipsychotics',
                'units_number' => 1,
                'medicine_unit_id' => 15,
                'barcode' => '6222014003530',
            ],
            [
                'en_name' => 'abilify 10 mg 10 tabs.',
                'ar_name' => 'ابيليفاي 10مجم 10 اقراص',
                'price' => 220.5,
                'scientific_name' => 'aripiprazole',
                'medicine_company_id' => 42,
                'usage' => 'psychiatric.antipsychotics',
                'units_number' => 1,
                'medicine_unit_id' => 15,
                'barcode' => '6222014003547',
            ],
            [
                'en_name' => 'a1 cream 100 gm',
                'ar_name' => 'ايه وان بيبي كريم 100جم',
                'price' => 45,
                'scientific_name' => 'castor oil+zinc oxide+arachis oil+bees wax',
                'medicine_company_id' => 23,
                'usage' => 'soothing agent',
                'units_number' => 1,
                'medicine_unit_id' => 3,
                'barcode' => '6223003930479',
            ],
            [
                'en_name' => 'a1 cream 50 gm',
                'ar_name' => 'ايه وان كريم 50 جم',
                'price' => 30,
                'scientific_name' => 'castor oil+zinc oxide+arachis oil+bees wax',
                'medicine_company_id' => 23,
                'usage' => 'soothing topical',
                'units_number' => 1,
                'medicine_unit_id' => 3,
                'barcode' => '6223003932084',
            ],
            [
                'en_name' => 'acitretin 10mg 30 caps.',
                'ar_name' => 'اسيتريتن 10مجم 30 كبسولة',
                'price' => 87,
                'scientific_name' => 'acitretin',
                'medicine_company_id' => 33,
                'usage' => 'psoriasis',
                'units_number' => 3,
                'medicine_unit_id' => 2,
                'barcode' => '6224000808006',
            ],
            [
                'en_name' => 'acitretin 25mg 30 caps.',
                'ar_name' => 'اسيتريتين 25مجم 30 كبسولة',
                'price' => 135,
                'scientific_name' => 'acitretin',
                'medicine_company_id' => 33,
                'usage' => 'psoriasis',
                'units_number' => 3,
                'medicine_unit_id' => 2,
                'barcode' => '6224000808013',
            ],
            [
                'en_name' => 'acapril 20mg 20 tab.',
                'ar_name' => 'اكابريل 20مجم 20 قرص',
                'price' => 18,
                'scientific_name' => 'enalapril',
                'medicine_company_id' => 6,
                'usage' => 'antihypertensive.ace',
                'units_number' => 2,
                'medicine_unit_id' => 15,
                'barcode' => '6224000875152',
            ],
            [
                'en_name' => 'acapril 5 mg 10 tab.',
                'ar_name' => 'اكابريل 5مجم 10 اقراص',
                'price' => 6.75,
                'scientific_name' => 'enalapril',
                'medicine_company_id' => 6,
                'usage' => 'antihypertensive.ace',
                'units_number' => 1,
                'medicine_unit_id' => 15,
                'barcode' => '6224000875190',
            ],
            [
                'en_name' => 'acidipan oral susp. 180 ml',
                'ar_name' => 'اسيديبان معلق 180 مل',
                'price' => 20.5,
                'scientific_name' => 'aluminium hydroxide+magnesium hydroxide+simethicone',
                'medicine_company_id' => 55,
                'usage' => 'antacid',
                'units_number' => 1,
                'medicine_unit_id' => 12,
                'barcode' => '6224007308677',
            ],
            [
                'en_name' => 'acetothyme 10 sachets',
                'ar_name' => 'اسيتوثايم 10 اكياس',
                'price' => 55,
                'scientific_name' => 'n-acetyl l-cysteine+thyme+vitamin c',
                'medicine_company_id' => 17,
                'usage' => 'mucolytic soothing agent and antioxidant',
                'units_number' => 1,
                'medicine_unit_id' => 9,
                'barcode' => '6224007364376',
            ],
            [
                'en_name' => '5-fluorouracil-ebewe 250mg/5ml i.v. vial',
                'ar_name' => 'فلورويوراسيل 250مجم/10مل 5 امبولات وريد',
                'price' => 50,
                'scientific_name' => 'fluorouracil',
                'medicine_company_id' => 51,
                'usage' => 'antineoplastic',
                'units_number' => 1,
                'medicine_unit_id' => 17,
                'barcode' => '9088881320685',
            ],
            [
                'en_name' => 'abc mocotive topical spray 70 ml',
                'ar_name' => 'ايه بي سي موكوتيف سبراي 70 مل',
                'price' => 30,
                'scientific_name' => 'alcohol 70%+tea tree oil+vit.e+chamomile+aluminium chloride hexahydrate+glycerin',
                'medicine_company_id' => 1,
                'usage' => 'antiseptic',
                'units_number' => 1,
                'medicine_unit_id' => 11,
                'barcode' => '',
            ],
            [
                'en_name' => 'accofil 30 miu/0.5ml 5 prefilled syringes',
                'ar_name' => 'اكوفيل 30مليون وحدة/0.5مل 5 سرنجات معبأة',
                'price' => 1625,
                'scientific_name' => 'filgrastim',
                'medicine_company_id' => 2,
                'usage' => 'granulocyte colony-stimulating factor (g-csf)',
                'units_number' => 5,
                'medicine_unit_id' => 13,
                'barcode' => '',
            ],
            [
                'en_name' => 'abstain sr 150 mg 20 tab.',
                'ar_name' => 'ابستين اس ار 150مجم 20 قرص',
                'price' => 20,
                'scientific_name' => 'bupropion',
                'medicine_company_id' => 3,
                'usage' => 'psychiatric.antidepressants',
                'units_number' => 2,
                'medicine_unit_id' => 15,
                'barcode' => '',
            ],
            [
                'en_name' => 'acemetacin stada 60mg 20 caps.',
                'ar_name' => 'اسيميتاسين ستادا 60 مجم 20 كبسولة',
                'price' => 24,
                'scientific_name' => 'acemetacin',
                'medicine_company_id' => 4,
                'usage' => 'nsaid.analgesic',
                'units_number' => 2,
                'medicine_unit_id' => 2,
                'barcode' => '',
            ],
            [
                'en_name' => 'achterctin 0.5% 60ml lotion',
                'ar_name' => 'اكتريكتين 0.5% - 60 مل لوشن',
                'price' => 8,
                'scientific_name' => 'ivermectin',
                'medicine_company_id' => 5,
                'usage' => 'anthelmintic',
                'units_number' => 1,
                'medicine_unit_id' => 7,
                'barcode' => '',
            ],
            [
                'en_name' => 'abrammune 100 mg 50 capsules',
                'ar_name' => 'ابراميون 100 مجم 50 كبسول',
                'price' => 410,
                'scientific_name' => 'cyclosporin',
                'medicine_company_id' => 7,
                'usage' => 'immunosuppressant',
                'units_number' => 5,
                'medicine_unit_id' => 2,
                'barcode' => '',
            ],
            [
                'en_name' => 'abrammune 100mg/ml syrup',
                'ar_name' => 'ابراميون 100مجم زجاجة شراب',
                'price' => 410,
                'scientific_name' => 'cyclosporin',
                'medicine_company_id' => 7,
                'usage' => 'immunosuppressants',
                'units_number' => 1,
                'medicine_unit_id' => 14,
                'barcode' => '',
            ],
            [
                'en_name' => 'abrammune 25 mg 10 caps.',
                'ar_name' => 'ابراميون 25مجم 10 كبسول',
                'price' => 24,
                'scientific_name' => 'cyclosporin',
                'medicine_company_id' => 7,
                'usage' => 'immunosuppressants',
                'units_number' => 1,
                'medicine_unit_id' => 2,
                'barcode' => '',
            ],
            [
                'en_name' => 'abrammune 50 mg 10 caps.',
                'ar_name' => 'ابراميون 50مجم 10 كبسولات',
                'price' => 44,
                'scientific_name' => 'cyclosporin',
                'medicine_company_id' => 7,
                'usage' => 'immunosuppressant',
                'units_number' => 1,
                'medicine_unit_id' => 2,
                'barcode' => '',
            ],
            [
                'en_name' => 'abrammune 50mg/ml syrup',
                'ar_name' => 'ابراميون 50 مجم شراب زجاجة',
                'price' => 220,
                'scientific_name' => 'cyclosporin',
                'medicine_company_id' => 7,
                'usage' => 'immunosuppressant',
                'units_number' => 1,
                'medicine_unit_id' => 14,
                'barcode' => '',
            ],
            [
                'en_name' => 'accolate 20mg 28 tab.',
                'ar_name' => 'اكولات 20 مجم 28 قرص',
                'price' => 82,
                'scientific_name' => 'zafirlukast',
                'medicine_company_id' => 9,
                'usage' => 'leukotriene d4 and e4 antagonist',
                'units_number' => 4,
                'medicine_unit_id' => 15,
                'barcode' => '',
            ],
            [
                'en_name' => 'aceliofinaz 100 mg 20 f.c. tab.',
                'ar_name' => 'اسيليوفيناز 100 مجم 20 قرص',
                'price' => 39,
                'scientific_name' => 'aceclofenac',
                'medicine_company_id' => 10,
                'usage' => 'nsaid.acetic acid derivatives',
                'units_number' => 2,
                'medicine_unit_id' => 15,
                'barcode' => '',
            ],
            [
                'en_name' => 'abc immune 10 sachets',
                'ar_name' => 'ايه بي سي اميون 10 اكياس',
                'price' => 40,
                'scientific_name' => 'vitamin c+zinc',
                'medicine_company_id' => 11,
                'usage' => 'vitamin c',
                'units_number' => 1,
                'medicine_unit_id' => 9,
                'barcode' => '',
            ],
            [
                'en_name' => 'abc lemon & honey syrup 60 ml',
                'ar_name' => 'ايه بي سي ليمون & عسل شراب 60 مل',
                'price' => 54,
                'scientific_name' => 'natural honey+citric acid+lemon juice concentrate',
                'medicine_company_id' => 11,
                'usage' => 'multivitamins',
                'units_number' => 1,
                'medicine_unit_id' => 14,
                'barcode' => '',
            ],
            [
                'en_name' => 'abc omega 3-6-9 syrup 60 ml',
                'ar_name' => 'ايه بي سي اوميجا 3-6-9 شراب 60 مل',
                'price' => 88,
                'scientific_name' => 'wheat germ oil',
                'medicine_company_id' => 11,
                'usage' => 'omega 3',
                'units_number' => 1,
                'medicine_unit_id' => 14,
                'barcode' => '',
            ],
            [
                'en_name' => 'abilify 10 mg 10 discmelt orally dis.tabs.',
                'ar_name' => 'ابيليفاي 10مجم ديسكملت 10 اقراص ذائبة بالفم',
                'price' => 190,
                'scientific_name' => 'aripiprazole',
                'medicine_company_id' => 12,
                'usage' => 'psychiatric.antipsychotics',
                'units_number' => 1,
                'medicine_unit_id' => 15,
                'barcode' => '',
            ],
            [
                'en_name' => 'abilify 15 mg 10 discmelt orally dis.tabs.',
                'ar_name' => 'ابيليفاي 15مجم 10 ديسكملت اقراص ذائبة بالفم',
                'price' => 270,
                'scientific_name' => 'aripiprazole',
                'medicine_company_id' => 12,
                'usage' => 'psychiatric.antipsychotics',
                'units_number' => 1,
                'medicine_unit_id' => 15,
                'barcode' => '',
            ],
            [
                'en_name' => 'abraxane 100mg vial ss',
                'ar_name' => 'ابراكسان 100مجم فيال اس اس',
                'price' => 7137,
                'scientific_name' => 'paclitaxel protein-bound',
                'medicine_company_id' => 13,
                'usage' => 'antineoplastic',
                'units_number' => 1,
                'medicine_unit_id' => 17,
                'barcode' => '',
            ],
            [
                'en_name' => 'abilia 15mg 30 f.c.tabs.',
                'ar_name' => 'ابيليا 15مجم 30 قرص',
                'price' => 105,
                'scientific_name' => 'aripiprazole',
                'medicine_company_id' => 14,
                'usage' => 'psychiatric.antipsychotics',
                'units_number' => 3,
                'medicine_unit_id' => 15,
                'barcode' => '',
            ],
            [
                'en_name' => 'abilia 20mg 30 f.c.tabs.',
                'ar_name' => 'ابيليا 20مجم 30 قرص',
                'price' => 120,
                'scientific_name' => 'aripiprazole',
                'medicine_company_id' => 14,
                'usage' => 'psychiatric.antipsychotics',
                'units_number' => 3,
                'medicine_unit_id' => 15,
                'barcode' => '',
            ],
            [
                'en_name' => '5fu 250mg/5ml vial',
                'ar_name' => '5-فلورويوراسيل 250مجم/5مل فيال',
                'price' => 9,
                'scientific_name' => 'fluorouracil',
                'medicine_company_id' => 15,
                'usage' => 'antineoplastic',
                'units_number' => 1,
                'medicine_unit_id' => 17,
                'barcode' => '',
            ],
            [
                'en_name' => 'acetylcystdar 600 mg 12 eff. tabs',
                'ar_name' => 'استيل سيستدار 600 مجم 12 اقراص فوارة',
                'price' => 35,
                'scientific_name' => 'acetylcysteine',
                'medicine_company_id' => 16,
                'usage' => 'mucolytic',
                'units_number' => 1,
                'medicine_unit_id' => 15,
                'barcode' => '',
            ],
            [
                'en_name' => 'aceclocopa 100 mg 20 f.c. tab.',
                'ar_name' => 'اسيكلوكوبا 100 مجم 20 قرص',
                'price' => 22.5,
                'scientific_name' => 'aceclofenac',
                'medicine_company_id' => 18,
                'usage' => 'nsaid.acetic acid derivatives',
                'units_number' => 2,
                'medicine_unit_id' => 15,
                'barcode' => '',
            ],
            [
                'en_name' => 'aberto cream 75 gm',
                'ar_name' => 'ابيرتو كريم 75 جرام',
                'price' => 49.9,
                'scientific_name' => 'glycerin+ext (licorice-green-cucumber)+paraffin oil+vitamin e&c+kojic acid+titanium dioxide',
                'medicine_company_id' => 19,
                'usage' => 'whitening topical',
                'units_number' => 1,
                'medicine_unit_id' => 3,
                'barcode' => '',
            ],
            [
                'en_name' => 'acetalgan 1 gm/100ml sol. for i.v. vial',
                'ar_name' => 'اسيتالجان 1جم/100مل محلول وريدي فيال',
                'price' => 22.5,
                'scientific_name' => 'paracetamol(acetaminophen)',
                'medicine_company_id' => 20,
                'usage' => 'antipyretic',
                'units_number' => 1,
                'medicine_unit_id' => 10,
                'barcode' => '',
            ],
            [
                'en_name' => 'accent cream 30 gm',
                'ar_name' => 'اكسنت كريم',
                'price' => 30,
                'scientific_name' => '',
                'medicine_company_id' => 21,
                'usage' => 'healing topical',
                'units_number' => 1,
                'medicine_unit_id' => 3,
                'barcode' => '',
            ],
            [
                'en_name' => 'accent cream 50 gm',
                'ar_name' => 'اكسنت كريم 50 جم',
                'price' => 50,
                'scientific_name' => '',
                'medicine_company_id' => 21,
                'usage' => 'healing topical',
                'units_number' => 1,
                'medicine_unit_id' => 3,
                'barcode' => '',
            ],
            [
                'en_name' => 'acik cream 50 gm',
                'ar_name' => 'اسيك كريم 50 جرام',
                'price' => 69.5,
                'scientific_name' => 'salicylic acid+lavender oil+witch hazel extract+retinol+lactic acid+propolis extract+tea tree oil+thyme oil+panthenol+vitamin e+sulfur',
                'medicine_company_id' => 22,
                'usage' => 'skin care.acne',
                'units_number' => 1,
                'medicine_unit_id' => 3,
                'barcode' => '',
            ],
            [
                'en_name' => 'acesolv 2% syrup 60ml',
                'ar_name' => 'اسيسولف 2% شراب 60 مل',
                'price' => 8,
                'scientific_name' => 'acetylcysteine',
                'medicine_company_id' => 24,
                'usage' => 'mucolytic',
                'units_number' => 1,
                'medicine_unit_id' => 14,
                'barcode' => '',
            ],
            [
                'en_name' => 'acetorphan children 30mg oral sachet',
                'ar_name' => 'اسيتورفان 30مجم اطفال اكياس بالفم',
                'price' => 10,
                'scientific_name' => 'racecadotril',
                'medicine_company_id' => 25,
                'usage' => 'antidiarrheal',
                'units_number' => 1,
                'medicine_unit_id' => 9,
                'barcode' => '',
            ],
            [
                'en_name' => 'acetorphan infant 10mg oral sachets',
                'ar_name' => 'اسيتورفان رضع 10مجم أكياس بالفم',
                'price' => 5,
                'scientific_name' => 'racecadotril',
                'medicine_company_id' => 25,
                'usage' => 'antidiarrheal',
                'units_number' => 1,
                'medicine_unit_id' => 9,
                'barcode' => '',
            ],
            [
                'en_name' => 'abilaxine 10mg 5 adult supp.',
                'ar_name' => 'ابيلاكسين 10 مجم لبوس كبار 5 اقماع',
                'price' => 4,
                'scientific_name' => 'bisacodyl',
                'medicine_company_id' => 26,
                'usage' => 'laxative',
                'units_number' => 1,
                'medicine_unit_id' => 12,
                'barcode' => '',
            ],            [
                'en_name' => 'abilaxine 5mg 5 infantile supp.',
                'ar_name' => 'ابيلاكسين 5مجم لبوس اطفال 5 اقماع',
                'price' => 3.2,
                'scientific_name' => 'bisacodyl',
                'medicine_company_id' => 26,
                'usage' => 'laxative',
                'units_number' => 1,
                'medicine_unit_id' => 12,
                'barcode' => '',
            ],
            [
                'en_name' => 'aceto-v vaginal wash 250 ml',
                'ar_name' => 'اسيتو في غسول مهبلي 250 مل',
                'price' => 37.5,
                'scientific_name' => 'chlorhexidine',
                'medicine_company_id' => 27,
                'usage' => 'vaginal care',
                'units_number' => 1,
                'medicine_unit_id' => 16,
                'barcode' => '',
            ],
            [
                'en_name' => '1 2 3 (one two three) 20 f.c.tabs.',
                'ar_name' => 'ون تو ثري 20 قرص',
                'price' => 24,
                'scientific_name' => 'pseudoephedrine+paracetamol+chlorpheniramine',
                'medicine_company_id' => 28,
                'usage' => 'cold drugs',
                'units_number' => 2,
                'medicine_unit_id' => 15,
                'barcode' => '',
            ],
            [
                'en_name' => '1 2 3 (one two three) syrup 120 ml',
                'ar_name' => 'ون تو ثري شراب 120 مل',
                'price' => 19.5,
                'scientific_name' => 'pseudoephedrine+paracetamol+chlorpheniramine',
                'medicine_company_id' => 28,
                'usage' => 'cold drugs',
                'units_number' => 1,
                'medicine_unit_id' => 14,
                'barcode' => '',
            ],
            [
                'en_name' => 'acetamex 250mg 20 tab.',
                'ar_name' => 'اسيتامكس 250مجم 20 قرص',
                'price' => 6,
                'scientific_name' => 'acetazolamide',
                'medicine_company_id' => 29,
                'usage' => 'diuretic.carbonic anhydrase inhibitors',
                'units_number' => 2,
                'medicine_unit_id' => 15,
                'barcode' => '',
            ],
            [
                'en_name' => 'acadia destina baby cream 60 gm',
                'ar_name' => 'اكاديا ديستينا كريم اطفال 60 جم',
                'price' => 49,
                'scientific_name' => 'zinc oxide+aloe vera extract+olive oil+panthenol+lanolin+oat extract+glycerin+lavender oil+vitamin e',
                'medicine_company_id' => 30,
                'usage' => 'diaper rash',
                'units_number' => 1,
                'medicine_unit_id' => 3,
                'barcode' => '',
            ],
            [
                'en_name' => 'acadia destina lotion 120 ml',
                'ar_name' => 'اكاديا ديستينا لوسيون 120 مل',
                'price' => 85,
                'scientific_name' => 'zinc oxide+aloe vera extract+olive oil',
                'medicine_company_id' => 30,
                'usage' => 'moisturizing topicals',
                'units_number' => 1,
                'medicine_unit_id' => 8,
                'barcode' => '',
            ],
            [
                'en_name' => 'acadia herashow oil spray 120 ml',
                'ar_name' => 'اكاديا هيرشو زيت بخاخ 120 مل',
                'price' => 149,
                'scientific_name' => 'black seed oil+sesame oil+olive oil',
                'medicine_company_id' => 30,
                'usage' => 'hair care',
                'units_number' => 1,
                'medicine_unit_id' => 8,
                'barcode' => '',
            ],
            [
                'en_name' => 'acenewrax 200 mg 10 sachets',
                'ar_name' => 'اسينيوراكس 200مجم 10 اكياس',
                'price' => 20,
                'scientific_name' => 'acetylcysteine',
                'medicine_company_id' => 31,
                'usage' => 'mucolytic',
                'units_number' => 1,
                'medicine_unit_id' => 9,
                'barcode' => '',
            ],
            [
                'en_name' => 'acenewrax 600 mg 10 sachets',
                'ar_name' => 'اسينيوراكس 600مجم 10 اكياس',
                'price' => 44,
                'scientific_name' => 'acetylcysteine',
                'medicine_company_id' => 31,
                'usage' => 'mucolytic',
                'units_number' => 1,
                'medicine_unit_id' => 9,
                'barcode' => '',
            ],
            [
                'en_name' => 'acetaprofen 120ml susp.',
                'ar_name' => 'اسيتابروفين 120 مل معلق',
                'price' => 6.75,
                'scientific_name' => 'ibuprofen+paracetamol',
                'medicine_company_id' => 32,
                'usage' => 'analgesic.antipyretic.nsaid',
                'units_number' => 1,
                'medicine_unit_id' => 12,
                'barcode' => '',
            ],
            [
                'en_name' => 'abital oral spray 30 ml',
                'ar_name' => 'ابيتال بخاخ فموي 30 مل',
                'price' => 15,
                'scientific_name' => 'melaleuca alternifolia extract+thymus extract+mentha piperita extract+salvia officinalis extract+pro',
                'medicine_company_id' => 34,
                'usage' => 'oral care',
                'units_number' => 1,
                'medicine_unit_id' => 11,
                'barcode' => '',
            ],
            [
                'en_name' => 'abstral 100mcg 10 sublingual tabs.',
                'ar_name' => 'ابسترال 100مكجم 10 قرص تحت اللسان',
                'price' => 1184,
                'scientific_name' => 'fentanyl',
                'medicine_company_id' => 35,
                'usage' => 'analgesics.opioid',
                'units_number' => 1,
                'medicine_unit_id' => 15,
                'barcode' => '',
            ],
            [
                'en_name' => 'abstral 200mcg 10 sublingual tabs.',
                'ar_name' => 'ابيسترال 200مكجم 10 قرص تحت اللسان',
                'price' => 1184,
                'scientific_name' => 'fentanyl',
                'medicine_company_id' => 35,
                'usage' => 'analgesics.opioid',
                'units_number' => 1,
                'medicine_unit_id' => 15,
                'barcode' => '',
            ],
            [
                'en_name' => 'abstral 400mcg 10 sublingual tabs',
                'ar_name' => 'ابسترال 400مكجم 10 اقراص تحت اللسان',
                'price' => 1184,
                'scientific_name' => 'fentanyl',
                'medicine_company_id' => 35,
                'usage' => 'analgesics.opioid',
                'units_number' => 1,
                'medicine_unit_id' => 15,
                'barcode' => '',
            ],
            [
                'en_name' => 'acerumen ear spray 40 ml',
                'ar_name' => 'اسيريومين بخاخ الأذن 40 مل',
                'price' => 69,
                'scientific_name' => '',
                'medicine_company_id' => 36,
                'usage' => 'ear wax remover',
                'units_number' => 1,
                'medicine_unit_id' => 11,
                'barcode' => '',
            ],
            [
                'en_name' => 'acivirax 400mg 30 tabs.',
                'ar_name' => 'اسيفيراكس 400مجم 30 قرص',
                'price' => 112.5,
                'scientific_name' => 'acyclovir',
                'medicine_company_id' => 37,
                'usage' => 'antiviral.nucleoside',
                'units_number' => 3,
                'medicine_unit_id' => 15,
                'barcode' => '',
            ],
            [
                'en_name' => 'acicone susp. 120ml',
                'ar_name' => 'اسيكون 120 مل معلق',
                'price' => 4.75,
                'scientific_name' => 'magaldrate',
                'medicine_company_id' => 39,
                'usage' => 'antacid',
                'units_number' => 1,
                'medicine_unit_id' => 12,
                'barcode' => '',
            ],
            [
                'en_name' => 'acicone-s oral susp. 120ml',
                'ar_name' => 'اسيكون اس 120 مل معلق',
                'price' => 5,
                'scientific_name' => 'magaldrate+simethicone',
                'medicine_company_id' => 39,
                'usage' => 'antacid',
                'units_number' => 1,
                'medicine_unit_id' => 12,
                'barcode' => '',
            ],
            [
                'en_name' => 'aclasta 5mg/100ml soln. for inf.',
                'ar_name' => 'اكلاستا 5مجم/100مل',
                'price' => 1860,
                'scientific_name' => 'zoledronic acid',
                'medicine_company_id' => 40,
                'usage' => 'osteoporosis.bisphosphonates',
                'units_number' => 1,
                'medicine_unit_id' => 1,
                'barcode' => '',
            ],
            [
                'en_name' => 'acanthaprop 1mg/ml eye drops 10 ml',
                'ar_name' => 'قطرة أكانثابروب 1ملغ / مل نقط للعين 10 مل',
                'price' => 36,
                'scientific_name' => 'propamidine isethionate',
                'medicine_company_id' => 41,
                'usage' => '',
                'units_number' => 1,
                'medicine_unit_id' => 5,
                'barcode' => '',
            ],
            [
                'en_name' => 'abilify 5 mg 10 tabs.',
                'ar_name' => 'ابيليفاي 5مجم 10 اقراص',
                'price' => 134.5,
                'scientific_name' => 'aripiprazole',
                'medicine_company_id' => 42,
                'usage' => 'psychiatric.antipsychotics',
                'units_number' => 1,
                'medicine_unit_id' => 15,
                'barcode' => '',
            ],
            [
                'en_name' => 'acetoflu cold and flu 20 f.c. tabs.',
                'ar_name' => 'اسيتوفلو كولد اند فلو 20 قرص',
                'price' => 19,
                'scientific_name' => 'diphenhydramine+paracetamol(acetaminophen)+pseudoephedrine',
                'medicine_company_id' => 43,
                'usage' => 'cold products',
                'units_number' => 2,
                'medicine_unit_id' => 15,
                'barcode' => '',
            ],
            [
                'en_name' => 'aape renewal eye cream 20 ml',
                'ar_name' => 'ايبي كريم العين20جم',
                'price' => 420,
                'scientific_name' => '',
                'medicine_company_id' => 44,
                'usage' => 'eye contour',
                'units_number' => 1,
                'medicine_unit_id' => 3,
                'barcode' => '',
            ],
            [
                'en_name' => 'aape renewal face cream 50 ml',
                'ar_name' => 'ايبي كريم تجديد الوجه 50 جم',
                'price' => 750,
                'scientific_name' => '',
                'medicine_company_id' => 44,
                'usage' => 'skin care',
                'units_number' => 1,
                'medicine_unit_id' => 3,
                'barcode' => '',
            ],
            [
                'en_name' => 'aape renewal facial toner 130 ml',
                'ar_name' => 'ايبي تونر للتجديد 130 مل',
                'price' => 370,
                'scientific_name' => '',
                'medicine_company_id' => 44,
                'usage' => 'skin care',
                'units_number' => 1,
                'medicine_unit_id' => 8,
                'barcode' => '',
            ],
            [
                'en_name' => 'aape renewal serum 40 ml',
                'ar_name' => 'ايبي رينيوال سيروم 40 مل',
                'price' => 750,
                'scientific_name' => '',
                'medicine_company_id' => 44,
                'usage' => 'skin care',
                'units_number' => 1,
                'medicine_unit_id' => 8,
                'barcode' => '',
            ],
            [
                'en_name' => 'aape renewal sunscreen spf 45 - 60 ml',
                'ar_name' => 'ايبي رينيوال صن سكرين اس بي اف 45 - 60 مل',
                'price' => 225,
                'scientific_name' => '',
                'medicine_company_id' => 44,
                'usage' => 'sun block',
                'units_number' => 1,
                'medicine_unit_id' => 8,
                'barcode' => '',
            ],
            [
                'en_name' => 'absorbable selenium 200 mcg 100 caps. (illegal import)',
                'ar_name' => 'سيلينيوم قابل للامتصاص 200 ميكروغرام 100 كبسولة',
                'price' => 0,
                'scientific_name' => 'selenium',
                'medicine_company_id' => 45,
                'usage' => 'antioxidant',
                'units_number' => 10,
                'medicine_unit_id' => 2,
                'barcode' => '',
            ],
            [
                'en_name' => 'acai 1000 mg 60 softgels (illegal import)',
                'ar_name' => 'اكاي 1000 مجم 60 كبسولة هلامية',
                'price' => 0,
                'scientific_name' => 'acai extract',
                'medicine_company_id' => 45,
                'usage' => 'antioxidant',
                'units_number' => 3,
                'medicine_unit_id' => 2,
                'barcode' => '',
            ],
            [
                'en_name' => 'acetasee 1% eye drops (susp.) 5 ml',
                'ar_name' => 'اسيتاسى 1% نقط للعين 5 مل',
                'price' => 7.5,
                'scientific_name' => 'prednisolone',
                'medicine_company_id' => 46,
                'usage' => 'glucocorticoid',
                'units_number' => 1,
                'medicine_unit_id' => 5,
                'barcode' => '',
            ],
            [
                'en_name' => 'acetoflu cold and flu syrup 100 ml',
                'ar_name' => 'اسيتوفلو كولد اند فلو شراب 100 مل',
                'price' => 9.75,
                'scientific_name' => 'diphenhydramine+paracetamol(acetaminophen)+pseudoephedrine',
                'medicine_company_id' => 47,
                'usage' => 'cold drugs',
                'units_number' => 1,
                'medicine_unit_id' => 14,
                'barcode' => '',
            ],
            [
                'en_name' => 'aciclovir mylan 250mg 5 vial',
                'ar_name' => 'اسيكلوفير ميلان 250 مجم 5 فيال',
                'price' => 365,
                'scientific_name' => 'acyclovir',
                'medicine_company_id' => 48,
                'usage' => 'antiviral.nucleoside',
                'units_number' => 5,
                'medicine_unit_id' => 17,
                'barcode' => '',
            ],
            [
                'en_name' => 'aciclovir mylan 500 mg 5 vials',
                'ar_name' => 'اسيكلوفير ميلان 500مجم 5 فيال',
                'price' => 520,
                'scientific_name' => 'acyclovir',
                'medicine_company_id' => 48,
                'usage' => 'antiviral.nucleoside',
                'units_number' => 5,
                'medicine_unit_id' => 17,
                'barcode' => '',
            ],
            [
                'en_name' => 'acavio massage gel 50 gm',
                'ar_name' => 'اكافيو مساج جيل 50 جرام',
                'price' => 45,
                'scientific_name' => 'CAMPHOR + MENTOL CRYSTALS + EUCALYPTUS + ETHANOLOMINE EXTRACT GLYCERIN',
                'medicine_company_id' => 49,
                'usage' => 'massage cream',
                'units_number' => 1,
                'medicine_unit_id' => 6,
                'barcode' => '',
            ],
            [
                'en_name' => 'acetaminophen 125mg paed. supp.u.s.p.xxiii',
                'ar_name' => 'اسيتامينوفين 125مجم لبوس اطفال',
                'price' => 3,
                'scientific_name' => 'paracetamol',
                'medicine_company_id' => 50,
                'usage' => 'antipyretic.analgesic',
                'units_number' => 1,
                'medicine_unit_id' => 12,
                'barcode' => '',
            ],
            [
                'en_name' => 'acetaminophen 500mg 20 tab',
                'ar_name' => 'اسيتامينوفين 500مجم 20 اقراص',
                'price' => 15,
                'scientific_name' => 'paracetamol(acetaminophen)',
                'medicine_company_id' => 50,
                'usage' => 'antipyretic',
                'units_number' => 2,
                'medicine_unit_id' => 15,
                'barcode' => '',
            ],
            [
                'en_name' => 'acetoful for women 10 tabs.',
                'ar_name' => 'اسيتوفول للسيدات 10 اقراص',
                'price' => 10.5,
                'scientific_name' => 'pamabrom+paracetamol',
                'medicine_company_id' => 52,
                'usage' => 'menstrual pain releif',
                'units_number' => 1,
                'medicine_unit_id' => 15,
                'barcode' => '',
            ],
            [
                'en_name' => '4 wet intimate gel 100 ml',
                'ar_name' => 'فور ويت انتيميت جل 100 مل',
                'price' => 40,
                'scientific_name' => '',
                'medicine_company_id' => 53,
                'usage' => 'lubricant',
                'units_number' => 1,
                'medicine_unit_id' => 6,
                'barcode' => '',
            ],
            [
                'en_name' => 'abevac 1mg/ml vial',
                'ar_name' => 'ابيفاك 1مجم فيال 1 مل',
                'price' => 10,
                'scientific_name' => 'bee venom',
                'medicine_company_id' => 54,
                'usage' => 'vaccine',
                'units_number' => 1,
                'medicine_unit_id' => 17,
                'barcode' => '',
            ],
        ]);
    }
}
